version: "3.8"
services:

    postgres:
      image: postgres:13
      container_name: gintest-postgres
      environment:
        - "POSTGRES_DB=${DB_DATABASE}"
        - "POSTGRES_USER=${DB_USERNAME}"
        - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      volumes:
        - "${DOCKER_PGSQL_DATA}:/var/lib/postgresql/data"

    application:
      build:
        context: .
        dockerfile: docker/development/golang/Dockerfile
      container_name: gintest-application
      working_dir: /application
      volumes:
          - ./:/application
      depends_on:
        - postgres
      links:
        - postgres
      ports:
        - "${DOCKER_APP_PORT}:${GIN_PORT}"
