#!/bin/bash
#
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook copy to `./.git/hooks/` then change to executable file.

# should compilable
echo "compile..."
make clean all
echo "compile success"

# should pass test
echo "go test..."
go test ./tests/... -v -count=1
echo "go test success"

# python coding style fixer
echo "go format..."
git diff --cached --name-only --diff-filter=ACM | grep '.go$' | xargs gofmt -w -l | xargs git add
echo "go format success!!"

# add missing and remove unused modules
echo "go mod tidy.."
go mod tidy
git add go.sum go.mod
echo "go mod tidy success!!"

# generate docs
echo "generate docs.."
swag init
git add docs/
echo "generate docs success!!"
